spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/netplix
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: king0221
    jpa:
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: validate
      generate-ddl: false
      open-in-view: false
      show-sql: false